config/routes.rb
Rails.application.routes.draw do

  get 'reviews/new'
  get 'reviews/create'
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end

  get '/tagged', to: "restaurants#tagged", as: :tagged

  root to: "restaurants#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :food_items, dependent: :destroy
  has_many :reviews, dependent: :destroy
  searchkick
  acts_as_taggable_on :tags, :arrondissements
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :price, presence: true
  validates :section, presence: true
end

app/models/section.rb
class Section
  def self.all
    %w(entrees plats desserts)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController

  def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @food_item = FoodItem.new
  end

  def create
    @food_item = FoodItem.new(food_item_params)
    # we need `restaurant_id` to asssociate food_item with corresponding restaurant
    @food_item.restaurant = Restaurant.find(params[:restaurant_id])
    @food_item.save
  end

  private

  def food_item_params
    params.require(:food_item).permit(:name, :price, :description)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json

  def index
    @restaurants = Restaurant.all
    @search = params["search"]
    if @search.present?
      @name = @search["name"]
      @restaurants = Restaurant.search(@name)
    else
      @restaurants = Restaurant.all.sample(3)
    end

    @all_restaurants = Restaurant.all
    @liste_arrondissements = []
    @all_restaurants.each do |restaurant|
      @liste_arrondissements << restaurant.arrondissement_list.first.to_i
    end
    @liste_arrondissements.sort! { |a, b| a <=> b }
    @liste_arrondissements.uniq!
  end



  def most_used_tags
    @most_used_tags = ActsAsTaggableOn::Tag.most_used(3)
  end

  def menu
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurants = Restaurant.all
    @restaurant = Restaurant.find(params[:id])
    @related_restaurants = @restaurant.find_related_tags
    @reviews = Review.all
  end

  def tagged
    if params[:tag].present?
      @restaurants = Restaurant.tagged_with(params[:tag])
    else
      @restaurants = Restaurant.all
    end
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
      params.require(:restaurant).permit(:name, :description, :tag_list)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end


  def sections
    @restaurant = Restaurant.find(params[:restaurant_id])
    @sections = %w(entrées plats desserts)
  end

  private

  def review_params
    params.require(:review).permit(:content, :price, :section)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arrondissements_helper.rb
module ArrondissementsHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/food_items/new.html.erb
<%# raise %>

<%= simple_form_for [@restaurant, @food_item] do |f| %>
  <%= f.input :name %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.submit "add a food item", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParisCash</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="margin: 10%">
    <%= yield %>

  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>


  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<%= simple_form_for :search, url: root_path, method: "GET", html: {id: 'query' } do |f| %>
  <%= f.input :name, input_html: {value: "", placeholder: "Un restaurant, un thème", class: 'search-restaurant'} %>
  <%= f.submit "Chercher", class: "btn btn-primary" %>
<% end %>

<br><br>


<% found_restaurants_count = 0 %>



<% @restaurants.each do |r| %>

  <p><%= link_to r.name.titleize, restaurant_path(r) %></p>

  <% found_restaurants_count = found_restaurants_count + 1 %>

<% end %>

<i><%= found_restaurants_count%> restaurants trouvés</i>




<br><br>

<h2>Most used tags 🚨</h2>

<% ActsAsTaggableOn::Tag.most_used(3).each do |tag| %>

  <% if tag.name.to_i == 0 %>
    <%= link_to tag.name, tagged_path(tag: tag.name) %>
  <% end %>

<% end %>



<br><br>

  <h2>Les restaurants à faire en amoureux ❤</h2>

  <% Restaurant.tagged_with('en amoureux').sample(3).each do |restaurant| %>
    <p><%= link_to restaurant.name.titleize, restaurant_path(restaurant) %></p>
  <% end %>


  <h2>Les meilleurs restos Italiens 🇮🇹</h2>

  <% Restaurant.tagged_with('pizza').each do |restaurant| %>
    <p><%= link_to restaurant.name.titleize, restaurant_path(restaurant) %></p>
  <% end %>

<br><br>


<br><br>
<h3>Une soirée Italienne avec tes potes</h3>

<% Restaurant.tagged_with(['pizza', 'bonne soiree entre amis']).each do |restaurant| %>
  <p><%= link_to restaurant.name.titleize, restaurant_path(restaurant) %></p>
<% end %>

<br><br>


<h2>Les restaurants par localisation</h2>


<% @liste_arrondissements.each do |arr| %>

  <% if arr < 2 %>
    <p><%= link_to "#{arr}er arrondissement", tagged_path(tag: arr) %>
  <% else %>
    <p><%= link_to "#{arr}ème arrondissement", tagged_path(tag: arr) %>
  <% end %>

<% end %>





<!-- a restaurant have one menu -->

<!-- a menu has many section -->

<!-- a section has many food items -->

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>




<h1><%= @restaurant.name.titleize %> <%= @restaurant.id %></h1>
<h3><%= @restaurant.address %></h3>

<% if @restaurant.arrondissement_list.first %>
  <%= link_to @restaurant.arrondissement_list.first, tagged_path(tag: @restaurant.arrondissement_list.first) %>
<% else %>
  <%= @restaurant.arrondissement %>
<% end %>
<p><%= @restaurant.description %></p>

<div class="row">
<div class="col-xs-12 col-md-4 col-lg-4">
 <p>Les tags associés</p>
  <ul>
    <% if @restaurant.tag_list.length > 0 %>
      <% if @restaurant.tag_list.length > 3 %>
        <% @restaurant.tag_list.sample(3).each do |tag| %>
          <li><%= link_to tag, tagged_path(tag: tag) %></li>
        <% end %>
      <% else %>
        <% @restaurant.tag_list.each do |tag| %>
            <li><%= link_to tag, tagged_path(tag: tag) %></li>
        <% end %>
      <% end %>
    <% else %>
        <p>Pas encore de tag pour ce restaurant</p>
    <% end %>
  </ul>

</div>

<br><br>

<div class="col-xs-12 col-md-4 col-lg-4 offset-2">
  <% if @related_restaurants.any? %>
    <p>Vous aimerez aussi...</p>
  <% end %>


  <ul>
    <% @related_restaurants.sample(3).each do |r| %>
      <li><%= link_to r.name, restaurant_path(r) %></li>
    <% end %>
  </ul>
</div>
</div>

<p>Dans le même quartier</p>

<ul>
  <% @restaurants.each do |r| %>
    <% if !r.arrondissement.nil? %>
      <% if r.arrondissement == @restaurant.arrondissement && r.id != @restaurant.id %>
        <li><%= link_to r.name, restaurant_path(r) %></li>
      <% end %>
    <% end %>
  <% end %>
</ul>



<ul>

  <% @restaurants.each do |restaurant| %>

    <% if !restaurant.arrondissement_list.first.nil? %>
      <% if restaurant.arrondissement_list.first == @restaurant.arrondissement_list.first && restaurant.id != @restaurant.id %>
        <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
    <% end %>
    <% end %>

  <% end %>

</ul>


<h2>Menu</h2>

<% Section.all.each do |section| %>
  <div class="col-md-4">
    <h2><%= section.titleize %></h2>
    <% @reviews.each do |review| %>
      <% if review.section == section %>
        <p><%= review.content.titleize %> <u><%= review.price %> €</u> </p>
      <% end %>
    <% end %>
  </div>
<% end %>



<%= link_to 'home', restaurants_path %>
<%= link_to 'new food item', new_restaurant_review_path(@restaurant) %>

app/views/restaurants/tagged.html.erb
<%# params[:tag].to_i %>
  <% if params[:tag].to_i.between?(1, 21) %>
    <h1><%= params[:tag] %>ème arrondissement</h1>
  <% else %>
    <h1><%= params[:tag] %></h1>
  <% end %>


<% @restaurants = @restaurants.uniq %>

<ul>
  <% @restaurants.each do |restaurant|%>
    <p><%= link_to restaurant.name.titleize, restaurant_path(restaurant) %></p>
  <% end %>
</ul>

<%= link_to 'restaurants'.titleize, restaurants_path %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Ajouter un nouveau plat</h1>

<div class="row">
  <div class="col-lg-5 offset-3">
    <%= simple_form_for [@restaurant, @review] do |f| %>


  <% if @review.errors.any? %>
  <p>Remplissez tous les champs !</p>
    <div class="errors-container">
      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :content %>
  <%= f.input :price %>
  <%= f.input :section, collection: [ "entrees", "plats", "desserts" ], input_html: { class: 'custom-select' } %>

  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>
  </div>
</div>
<br>